export const productConfig = {
  brand: {
    name: "CareNow",
    tagline: "Healthcare, delivered to your doorstep.",
    description:
      "Order medicines, book lab tests, consult doctors and arrange home care from one trusted marketplace.",
  },

  locale: {
    language: "en-IN",
    currency: "INR",
  },

  theme: {
    fontFamily: {
      sans: "Manrope, Inter, ui-sans-serif, system-ui, sans-serif",
    },
    colors: {
      background: "#F5FBFC",
      surface: "#FFFFFF",
      surfaceMuted: "#EEF7F8",
      primary: "#0E9F91",
      // Button fills and teal text use primaryDark: white on `primary` is ~3.3:1 and fails AA.
      primaryDark: "#08796F",
      primaryDeep: "#065E57",
      primarySoft: "#DDF5F1",
      secondary: "#2F80ED",
      secondaryText: "#1F64C4",
      secondarySoft: "#E8F1FF",
      text: "#12313A",
      textMuted: "#60747A",
      textSubtle: "#8A9A9F",
      border: "#D7E6E8",
      borderStrong: "#BFD3D6",
      success: "#1C9B62",
      successText: "#167A4D",
      successSoft: "#E5F7EE",
      warning: "#C98917",
      warningText: "#8A5A00",
      warningSoft: "#FFF3D6",
      danger: "#D94B55",
      dangerText: "#B4323C",
      dangerSoft: "#FDE8EA",
      rating: "#F2A916",
    },
    // Per-category icon tints seen on the reference category tiles.
    categoryTones: {
      medicines: { fg: "#C2415A", bg: "#FCE9EE" },
      "lab-tests": { fg: "#2F6FD6", bg: "#E8F1FF" },
      doctors: { fg: "#0E8C80", bg: "#DDF5F1" },
      "home-care": { fg: "#1C8B5A", bg: "#E3F6EC" },
      "health-packages": { fg: "#3F8A3A", bg: "#EAF6E7" },
    },
    radius: {
      sm: 8,
      md: 12,
      lg: 16,
      xl: 22,
      full: 999,
    },
    // [font-size px, line-height px]
    typography: {
      display: [32, 38],
      h1: [26, 32],
      h2: [20, 28],
      h3: [17, 24],
      body: [15, 24],
      sm: [13, 20],
      xs: [12, 16],
    },
    shadows: {
      card: "0 1px 2px rgba(18, 49, 58, 0.04), 0 2px 10px rgba(18, 49, 58, 0.04)",
      raised: "0 4px 12px rgba(18, 49, 58, 0.06), 0 12px 32px rgba(18, 49, 58, 0.06)",
      nav: "0 -4px 16px rgba(18, 49, 58, 0.06)",
    },
    spacingUnit: 4,
    maxContentWidth: 1280,
  },

  navigation: {
    desktop: [
      { key: "home", label: "Home", href: "/", icon: "home" },
      { key: "explore", label: "Explore", href: "/explore", icon: "explore" },
      { key: "orders", label: "Orders", href: "/orders", icon: "orders" },
      { key: "health", label: "Health", href: "/health", icon: "health" },
    ],
    mobile: [
      { key: "home", label: "Home", href: "/", icon: "home" },
      { key: "explore", label: "Explore", href: "/explore", icon: "explore" },
      { key: "orders", label: "Orders", href: "/orders", icon: "orders" },
      { key: "health", label: "Health", href: "/health", icon: "health" },
      { key: "profile", label: "Profile", href: "/profile", icon: "profile" },
    ],
    headerActions: [
      { key: "notifications", label: "Notifications", href: "/notifications", icon: "bell" },
      { key: "cart", label: "Cart", href: "/cart", icon: "cart", showOnMobile: true },
      { key: "profile", label: "Profile", href: "/profile", icon: "profile" },
    ],
  },

  categories: [
    {
      key: "medicines",
      label: "Medicines",
      description: "OTC and prescription medicines",
      href: "/medicines",
      icon: "medicines",
    },
    {
      key: "lab-tests",
      label: "Lab Tests",
      description: "Home sample collection",
      href: "/lab-tests",
      icon: "lab-tests",
    },
    {
      key: "doctors",
      label: "Doctors",
      description: "Online and in‑person consultations",
      href: "/doctors",
      icon: "doctors",
    },
    {
      key: "home-care",
      label: "Home Care",
      description: "Nursing, physiotherapy and more",
      href: "/home-care",
      icon: "home-care",
    },
    {
      key: "health-packages",
      label: "Health Packages",
      description: "Preventive and wellness plans",
      href: "/health-packages",
      icon: "health-packages",
    },
  ],

  medicineRules: {
    otc: {
      label: "OTC / Non-prescription",
      shortLabel: "OTC",
      description: "Prescription is not required for this product where permitted.",
      tone: "neutral",
      icon: "check",
    },
    prescription: {
      label: "Prescription required",
      shortLabel: "Prescription required",
      description: "A valid prescription must be uploaded and verified before fulfillment.",
      tone: "warning",
      icon: "prescription",
    },
    restricted: {
      label: "Restricted / special process",
      shortLabel: "Restricted",
      description: "This item is not available through the standard CareNow checkout flow.",
      tone: "danger",
      icon: "restricted",
    },
  },

  statuses: {
    prescription: [
      { key: "uploaded", label: "Prescription uploaded", description: "We've received your prescription." },
      {
        key: "under-review",
        label: "Under review",
        description: "A pharmacist is verifying your prescription. This usually takes 10–30 minutes.",
      },
      { key: "approved", label: "Approved", description: "You'll be notified once it's verified." },
      { key: "preparing", label: "Preparing order", description: "The pharmacy will start packing." },
      { key: "out-for-delivery", label: "Out for delivery", description: "We'll notify you when it's on the way." },
      { key: "delivered", label: "Delivered", description: "Your order has been delivered." },
    ],
    prescriptionClarification: {
      key: "needs-clarification",
      label: "Needs clarification",
      description: "The pharmacist couldn't read the dosage. Upload a clearer photo to continue.",
    },
    // Delivery stages for a paid order.
    order: [
      { key: "confirmed", label: "Order confirmed", description: "Payment received. The pharmacy has your order." },
      { key: "preparing", label: "Preparing order", description: "The pharmacist is packing your medicines." },
      { key: "out-for-delivery", label: "Out for delivery", description: "Your delivery partner is on the way." },
      { key: "delivered", label: "Delivered", description: "Handed over at your door." },
    ],
    orderVerifiedStep: { key: "prescription-verified", label: "Prescription verified", description: "A pharmacist approved your prescription." },
    orderCancelled: { key: "cancelled", label: "Cancelled", description: "This order was cancelled. Any payment is refunded in 3–5 working days." },
    orderPaymentFailed: { key: "payment-failed", label: "Payment failed", description: "The payment didn't go through. You weren't charged." },
  },

  ui: {
    actions: {
      add: "Add",
      added: "Added",
      book: "Book",
      view: "View",
      // Accessible name for repeated card actions.
      itemLabel: "{action} {item}",
      select: "Select",
      selected: "Selected",
      viewAll: "See all",
      retry: "Try again",
      uploadPrescription: "Upload prescription",
      // Card-width label; the accessible name keeps the full action.
      uploadShort: "Upload",
      continue: "Continue",
      browse: "Browse services",
      remove: "Remove",
      notAvailable: "Not available",
    },
    time: {
      todayAt: "today at {time}",
      onDayAt: "on {day} at {time}",
    },
    search: {
      label: "Search CareNow",
      placeholder: "Search medicines, tests, doctors...",
      clear: "Clear search",
      submit: "Search",
    },
    header: {
      skipToContent: "Skip to content",
      primaryNav: "Primary",
      mobileNav: "Main",
      location: "Delivery location",
    },
    rating: {
      outOf: "out of 5",
      reviews: "reviews",
    },
    labels: {
      verified: "Verified",
    },
    units: {
      visit: "/ visit",
      session: "/ session",
      consult: "/ consult",
      day: "/ day",
    },
    // Shown by routes that later implementation steps will replace (catch-all page).
    placeholder: {
      title: "This screen is coming next",
      description: "It's part of the CareNow journey but hasn't been built in this prototype yet.",
      backHome: "Back to Home",
    },
    price: {
      off: "off",
      mrp: "MRP",
    },
    upload: {
      title: "Upload prescription",
      description: "Upload a clear image of your prescription. We'll verify it with the pharmacy.",
      cta: "Choose file",
      dropHint: "or drag and drop it here",
      dragging: "Drop your file to upload",
      formats: "JPG, PNG or PDF, up to 10 MB",
      accept: ["image/jpeg", "image/png", "application/pdf"],
      maxSizeMb: 10,
      errorType: "That file type isn't supported. Upload a JPG, PNG or PDF.",
      errorSize: "That file is larger than 10 MB. Upload a smaller photo or a compressed PDF.",
      replace: "Replace file",
    },
    timeline: {
      complete: "Completed",
      current: "In progress",
      upcoming: "Upcoming",
      attention: "Action needed",
      failed: "Not completed",
    },
    loading: {
      default: "Loading",
      results: "Finding options near you",
    },
    states: {
      emptySearchTitle: "No results found",
      emptySearchDescription: "Try a different spelling, or browse by category instead.",
      errorTitle: "We couldn't load this page",
      errorDescription: "Check your connection and try again. Your cart and prescriptions are safe.",
    },
  },

  content: {
    home: {
      greeting: "Good morning",
      heroTitle: "Your health, our priority",
      heroSubtitle: "Medicines, lab tests, doctors and home care, delivered fast and verified safely.",
      heroSubtitleShort: "Verified care, delivered.",
      heroCta: { label: "Explore services", href: "/explore" },
      heroSecondaryCta: { label: "Upload a prescription", shortLabel: "Upload", href: "/prescriptions/upload" },
      // Phone strip copy beside the short Upload button.
      heroUploadPrompt: "New prescription? A pharmacist checks it before delivery.",
      heroImage: {
        src: "/images/home/hero-clinician.jpg",
        alt: "Smiling clinician in teal scrubs",
        // Unsplash License: https://unsplash.com/photos/rm7rZYdl3rY
        credit: "Photo via Unsplash",
      },
      searchPlaceholder: "Search medicines, tests, doctors...",
      locationLabel: "Delivering to",
      sections: {
        categories: "What do you need today?",
        quickActions: "Quick actions",
        popular: "Popular services near you",
        providers: "Recommended providers",
        providerFilterLabel: "Filter providers",
        trust: "Why CareNow is safe to use",
        demoNotice: "Prototype with demo data: provider names, prices, ratings and orders are illustrative.",
      },
      activeOrder: {
        title: "Your active order",
        orderPrefix: "Order",
        stepOf: "Step {current} of {total}",
        track: "Track order",
        pharmacyNote: "Pharmacist at {pharmacy}",
        itemsMore: "{first} + {count} more",
        // Popular items that are already part of the active order.
        inOrderNote: "Already in order #{id}",
      },
      providerFilters: [
        { value: "all", label: "All" },
        { value: "doctor", label: "Doctors" },
        { value: "pharmacy", label: "Pharmacies" },
        { value: "lab", label: "Labs" },
      ],
      quickActions: [
        { key: "order-again", label: "Order Again", description: "{lastOrder}", href: "/orders", icon: "reorder", tone: "medicines" },
        { key: "book-lab", label: "Book a Lab Test", description: "Home sample collection", href: "/lab-tests", icon: "lab-tests", tone: "lab-tests" },
        { key: "find-doctor", label: "Find a Doctor", description: "Online or in‑clinic", href: "/doctors", icon: "doctors", tone: "doctors" },
        { key: "home-care", label: "Home Care", description: "Nursing at home", href: "/home-care", icon: "home-care", tone: "home-care" },
      ],
    },
    explore: {
      title: "Explore",
      resultsTitle: "Results for “{query}”",
      categoryNavLabel: "Browse by category",
      allLabel: "All",
      verifiedOnly: "Verified only",
      clearAll: "Clear search and filters",
      clearConcern: "Clear",
      resultCount: "{count} found",
      testsIncluded: "{count} tests included",
      notVerified: "Verification pending",
      // Medicines view entry into the prescription flow.
      uploadEntry: {
        label: "Have a prescription?",
        description: "Upload it once. A pharmacist verifies it before anything ships.",
      },
      sections: {
        services: "All healthcare services",
        concerns: "Popular categories",
        providers: "Nearby providers",
        providersNote: "Sorted by distance",
      },
      noProvidersTitle: "No verified providers nearby",
      noProvidersDescription: "Turn off “Verified only” to see providers still being checked.",
      // Health concerns that cut across categories; each matches items tagged with its key.
      concerns: [
        { key: "fever", label: "Fever & Cold", icon: "fever", tone: "medicines" },
        { key: "pain", label: "Pain Relief", icon: "pain", tone: "home-care" },
        { key: "heart", label: "Heart Care", icon: "heart", tone: "medicines" },
        { key: "thyroid", label: "Thyroid", icon: "thyroid", tone: "lab-tests" },
        { key: "vitamins", label: "Vitamins", icon: "vitamins", tone: "health-packages" },
        { key: "skin", label: "Skin Care", icon: "skin", tone: "doctors" },
        { key: "allergy", label: "Allergy", icon: "allergy", tone: "home-care" },
        { key: "bone", label: "Bone & Joint", icon: "bone", tone: "lab-tests" },
      ],
    },
    medicines: {
      title: "Medicines",
      subtitle: "Genuine medicines from verified pharmacies near you.",
      searchPlaceholder: "Search medicines by name",
      resultCount: "{count} medicines",
      filtersLabel: "Filters",
      categoryFilterLabel: "Medicine category",
      // Each value is a concern key that medicines are tagged with.
      categoryFilters: [
        { value: "all", label: "All" },
        { value: "fever", label: "Fever & Cold" },
        { value: "pain", label: "Pain Relief" },
        { value: "infection", label: "Infections" },
        { value: "allergy", label: "Allergy" },
        { value: "diabetes", label: "Diabetes" },
        { value: "vitamins", label: "Vitamins" },
      ],
      ruleFilterLabel: "Prescription type",
      ruleFilters: [
        { value: "all", label: "All" },
        { value: "otc", label: "OTC" },
        { value: "prescription", label: "Prescription" },
      ],
      sortLabel: "Sort by",
      sortOptions: [
        { value: "relevance", label: "Relevance" },
        { value: "price-asc", label: "Price: low to high" },
        { value: "price-desc", label: "Price: high to low" },
        { value: "rating", label: "Highest rated" },
      ],
      clearFilters: "Clear filters",
      emptyTitle: "No medicines match",
      emptyDescription: "Try another name, or clear the filters to see everything.",
      availability: {
        "in-stock": "In stock",
        "low-stock": "Only a few left",
        "out-of-stock": "Out of stock",
      },
      unavailableEverywhere: "Out of stock nearby",
      notSelectable: "Can't order until verified",
    },
    medicineDetail: {
      backToList: "All medicines",
      breadcrumbLabel: "Breadcrumb",
      manufacturer: "Manufacturer",
      pack: "Pack",
      availability: "Availability",
      infoTabsLabel: "Medicine information",
      tabs: { description: "Description", uses: "Uses", sideEffects: "Side effects" },
      noInfo: "Ask your pharmacist or doctor for details about this medicine.",
      infoNote: "For information only. Follow your doctor's or pharmacist's advice.",
      pharmaciesTitle: "Choose a pharmacy",
      pharmaciesLabel: "Pharmacies stocking this medicine",
      quantity: "Quantity",
      decrease: "Decrease quantity",
      increase: "Increase quantity",
      addToCart: "Add to cart",
      addedToCart: "Added {count} to your cart from {pharmacy}.",
      viewCart: "View cart",
      cartHref: "/cart",
      rx: {
        title: "Prescription required",
        body: "Upload a valid prescription. A pharmacist at {pharmacy} verifies it before this medicine can be added to your cart.",
        steps: ["Upload prescription", "Pharmacist verifies", "Add to cart and pay"],
        stepsLabel: "How prescription orders work",
      },
      rxInOrder: {
        title: "Your prescription is being reviewed",
        body: "This medicine is in order #{id}. You can't add it again until the pharmacist finishes.",
      },
      restricted: {
        title: "Not available on CareNow",
        body: "Controlled medicines need a special dispensing process under law and pharmacy policy, so they can't be ordered here.",
        action: "Consult a doctor",
      },
      outOfStock: {
        title: "Out of stock nearby",
        body: "No nearby pharmacy has this in stock right now. Check back later, or ask a pharmacist about an alternative.",
      },
    },
    // Labelled demo tooling: lets a presenter play the pharmacist, the bank and the courier.
    prototype: {
      title: "Prototype controls",
      description: "Simulates events that would come from the pharmacy, bank or courier in the real product.",
      approve: "Pharmacist approves",
      clarify: "Pharmacist asks for clarification",
      clarifyNote: "The dosage on page 1 isn't readable. Please upload a clearer, well-lit photo of the full prescription.",
      failNextPayment: "Next payment fails",
      advanceOrder: "Advance to next status",
      reset: "Reset demo data",
    },
    prescriptionUpload: {
      title: "Upload prescription",
      forMedicines: "For",
      chooseMedicine: "Which medicine is this prescription for?",
      choosePlaceholder: "Choose a prescription medicine",
      submit: "Submit for verification",
      submitting: "Uploading",
      needFile: "Choose a photo or PDF of your prescription first.",
      needMedicine: "Choose the medicine this prescription is for.",
      howTitle: "How verification works",
      how: [
        "Upload a clear photo or PDF of a valid prescription.",
        "A pharmacist checks the doctor, patient, medicine and dosage.",
        "Once approved, choose a pharmacy, then pay. Nothing ships before approval.",
      ],
      privacy: "Only the verifying pharmacist sees your prescription.",
    },
    verification: {
      title: "Prescription verification",
      reference: "Request {id}",
      uploadedAt: "Uploaded {time}",
      timelineLabel: "Verification progress",
      file: "Your file",
      medicines: "Medicines on this prescription",
      underReview: {
        title: "Under review",
        body: "A pharmacist at {pharmacy} is checking your prescription. This usually takes 10–30 minutes. We'll notify you when it's done.",
      },
      approved: {
        title: "Approved",
        body: "Your prescription was verified {when}. Choose a pharmacy to continue to cart.",
        action: "Choose pharmacy",
      },
      clarification: {
        title: "Needs clarification",
        body: "The pharmacist needs a clearer copy before approving.",
        noteLabel: "Pharmacist's note",
        reupload: "Upload a clearer copy",
        submit: "Resubmit for verification",
      },
      help: "Need help? Contact support",
      helpHref: "/support",
      nextStep: { key: "choose-pharmacy", label: "Choose pharmacy and pay", description: "Pick where to order from, then check out." },
      notFoundTitle: "We couldn't find this prescription",
      notFoundDescription: "It may have been removed. Upload it again to start a new verification.",
    },
    pharmacySelection: {
      title: "Choose a pharmacy",
      subtitle: "Pharmacies that stock everything on your approved prescription.",
      listLabel: "Available pharmacies",
      total: "Total for this prescription",
      missing: "Doesn't stock: {items}",
      notApproved: "This prescription isn't approved yet, so pharmacies can't be chosen.",
      addToCart: "Add to cart",
      noneTitle: "No nearby pharmacy stocks everything",
      noneDescription: "Contact support and we'll help source the rest.",
    },
    cart: {
      title: "Your cart",
      itemCount: "{count} items",
      fromPharmacy: "From {pharmacy}",
      prescriptionApproved: "Prescription approved",
      prescriptionMissing: "Needs an approved prescription",
      prescribedQuantity: "Quantity as prescribed",
      remove: "Remove {item}",
      couponLabel: "Coupon code",
      couponPlaceholder: "Enter code",
      couponApply: "Apply",
      couponRemove: "Remove coupon",
      couponApplied: "{code} applied: {description}",
      couponInvalid: "That code isn't valid. Check the spelling, or try CARE10.",
      summaryTitle: "Price details",
      itemTotal: "Item total",
      discount: "Coupon discount",
      delivery: "Delivery fee",
      expressFee: "Express delivery",
      free: "Free",
      total: "To pay",
      freeDeliveryHint: "Free delivery on orders above {amount} per pharmacy.",
      checkout: "Proceed to checkout",
      blocked: "Remove items that need an approved prescription to continue.",
      emptyTitle: "Your cart is empty",
      emptyDescription: "Add medicines from a verified pharmacy to get started.",
      emptyAction: "Browse medicines",
    },
    checkout: {
      title: "Checkout",
      steps: ["Cart", "Delivery", "Payment"],
      stepsLabel: "Checkout progress",
      addressTitle: "Delivery address",
      addressLabel: "Choose a delivery address",
      slotTitle: "Delivery time",
      slotLabel: "Choose a delivery time",
      laterSlotLabel: "Pick a slot",
      itemsTitle: "Items",
      continue: "Continue to payment",
      emptyRedirect: "Your cart is empty, so there's nothing to check out.",
    },
    payment: {
      title: "Payment",
      methodTitle: "Payment method",
      methodLabel: "Choose a payment method",
      upiLabel: "UPI ID",
      upiPlaceholder: "name@bank",
      upiHint: "We'll send a collect request to this UPI ID.",
      upiError: "Enter a UPI ID like name@bank.",
      walletLabel: "Wallet",
      savedCard: "Saved card",
      pay: "Pay {amount}",
      payShort: "Pay now",
      processingTitle: "Confirming payment",
      processingBody: "Waiting for your bank. Don't close this page.",
      failedTitle: "Payment didn't go through",
      failedBody: "Your bank declined the request. You weren't charged. Try again, or choose another payment method.",
      retry: "Try again",
      secure: "Payments are encrypted and processed by a licensed payment partner.",
    },
    tracking: {
      title: "Track order",
      placedAt: "Placed {time}",
      arrivingBy: "Arriving by {time}",
      arrivingSlot: "Arriving {slot}",
      timelineLabel: "Delivery progress",
      justPlaced: "Order placed. {pharmacy} has your order.",
      partnerTitle: "Your delivery partner",
      call: "Call",
      message: "Message",
      itemsTitle: "Items",
      addressTitle: "Delivering to",
      paidWith: "Paid with {method}",
      cancel: "Cancel order",
      cancelConfirm: "Cancel this order? Any payment is refunded in 3–5 working days.",
      cancelYes: "Yes, cancel order",
      cancelNo: "Keep order",
      delivered: "Delivered {time}. Hope you feel better soon.",
      reorder: "Order again",
      notFoundTitle: "We couldn't find this order",
      notFoundDescription: "Check your orders list for everything you've placed.",
      backToOrders: "Go to my orders",
    },
    orders: {
      title: "My orders",
      tabsLabel: "Order status",
      tabs: { ongoing: "Ongoing", past: "Past" },
      orderTitle: "Order #{id}",
      requestTitle: "Prescription {id}",
      placed: "{date}",
      itemsMore: "{first} + {count} more",
      track: "Track",
      view: "View",
      verify: "View status",
      retry: "Retry payment",
      reorder: "Order again",
      viewDetails: "View details",
      emptyOngoingTitle: "Nothing in progress",
      emptyOngoing: "Orders you place and prescriptions you upload appear here until delivery.",
      emptyPastTitle: "No past orders yet",
      emptyPast: "Delivered, cancelled and unpaid orders appear here.",
      browse: "Browse medicines",
    },
    trust: [
      { key: "verified", title: "Verified providers", description: "Every pharmacy, lab and doctor is checked before listing.", icon: "verified" },
      { key: "prescription", title: "Pharmacist verification", description: "Prescription medicines ship only after a pharmacist approves.", icon: "prescription" },
      { key: "payments", title: "Secure payments", description: "UPI, cards and wallets through encrypted checkout.", icon: "lock" },
      { key: "tracking", title: "Real-time tracking", description: "Follow every order from review to your door.", icon: "delivery" },
    ],
    emptyStates: {
      orders: "Your orders will appear here.",
      prescriptions: "No prescriptions uploaded yet.",
      appointments: "No upcoming appointments.",
    },
  },

  // Detail-page bases for item types that aren't marketplace categories.
  routes: {
    pharmacy: "/pharmacies",
    lab: "/labs",
    explore: "/explore",
    orders: "/orders",
    prescriptionUpload: "/prescriptions/upload",
  },

  demoData: {
    user: { firstName: "Ananya" },
    location: "Chennai, Tamil Nadu",
    locations: ["Chennai, Tamil Nadu", "Bengaluru, Karnataka", "Hyderabad, Telangana"],
    pharmacies: [
      { id: "careplus", name: "CarePlus Pharmacy", rating: 4.8, reviews: 2400, eta: "25–35 min", distance: "1.2 km", verified: true },
      { id: "mediquick", name: "MediQuick Chemists", rating: 4.6, reviews: 1800, eta: "30–40 min", distance: "2.8 km", verified: true },
      { id: "wellpath", name: "WellPath Pharmacy", rating: 4.5, reviews: 960, eta: "35–45 min", distance: "4.1 km", verified: false },
    ],
    doctors: [
      { id: "priya-sharma", name: "Dr. Priya Sharma", specialty: "General Physician", rating: 4.8, reviews: 2400, fee: 600, duration: "15 min", verified: true, concerns: ["fever", "thyroid"] },
      { id: "rahul-mehta", name: "Dr. Rahul Mehta", specialty: "Cardiologist", rating: 4.7, reviews: 1100, fee: 800, duration: "20 min", verified: true, concerns: ["heart"] },
      { id: "sneha-kapoor", name: "Dr. Sneha Kapoor", specialty: "Dermatologist", rating: 4.7, reviews: 870, fee: 700, duration: "20 min", verified: true, concerns: ["skin", "allergy"] },
      { id: "arjun-nair", name: "Dr. Arjun Nair", specialty: "Orthopedics", rating: 4.5, reviews: 640, fee: 750, duration: "30 min", verified: false, concerns: ["bone", "pain"] },
    ],
    // `price`/`mrp` are the listing price: the cheapest verified, in-stock offer. `offers` are per-pharmacy.
    // Manufacturers are fictional demo names.
    medicines: [
      {
        id: "paracetamol-500", name: "Paracetamol 500mg", price: 24, mrp: 30, pack: "Strip of 15 tablets", form: "tablet", rule: "otc", concerns: ["fever", "pain"],
        manufacturer: "Medisun Labs", rating: 4.7, reviews: 3200,
        description: "Paracetamol relieves mild to moderate pain and reduces fever. It is gentle on the stomach when taken as directed.",
        uses: ["Fever", "Headache", "Body ache", "Toothache"],
        sideEffects: ["Rare at normal doses", "Liver damage if the daily limit is exceeded"],
        offers: [
          { pharmacyId: "careplus", price: 24, stock: "in-stock" },
          { pharmacyId: "mediquick", price: 26, stock: "in-stock" },
          { pharmacyId: "wellpath", price: 25, stock: "low-stock" },
        ],
      },
      {
        id: "amoxicillin-500", name: "Amoxicillin 500mg", price: 85, mrp: 120, pack: "Strip of 10 capsules", form: "capsule", rule: "prescription", concerns: ["fever", "infection"],
        manufacturer: "Cureline Pharma", rating: 4.6, reviews: 1200,
        description: "Amoxicillin is a penicillin antibiotic used to treat bacterial infections. Finish the full course your doctor prescribes.",
        uses: ["Throat and ear infections", "Chest infections", "Urinary tract infections"],
        sideEffects: ["Nausea", "Diarrhoea", "Skin rash (stop and contact your doctor)"],
        offers: [
          { pharmacyId: "careplus", price: 85, stock: "in-stock" },
          { pharmacyId: "mediquick", price: 88, stock: "in-stock" },
          { pharmacyId: "wellpath", price: 90, stock: "out-of-stock" },
        ],
      },
      {
        id: "vitamin-d3-60k", name: "Vitamin D3 60K", price: 120, mrp: 140, pack: "Strip of 4 capsules", form: "capsule", rule: "prescription", concerns: ["vitamins", "bone"],
        manufacturer: "Healix Life Sciences", rating: 4.8, reviews: 2600,
        description: "A high-strength weekly Vitamin D3 (cholecalciferol) dose used to correct a confirmed deficiency.",
        uses: ["Vitamin D deficiency", "Bone health"],
        sideEffects: ["Nausea", "Raised calcium if overused"],
        offers: [
          { pharmacyId: "careplus", price: 120, stock: "in-stock" },
          { pharmacyId: "mediquick", price: 125, stock: "low-stock" },
        ],
      },
      {
        id: "cetirizine-10", name: "Cetirizine 10mg", price: 38, mrp: 45, pack: "Strip of 10 tablets", form: "tablet", rule: "otc", concerns: ["allergy"],
        manufacturer: "Novaris Generics", rating: 4.5, reviews: 1500,
        description: "Cetirizine is an antihistamine that relieves sneezing, runny nose and itchy, watery eyes caused by allergies.",
        uses: ["Hay fever", "Dust allergy", "Hives"],
        sideEffects: ["Drowsiness", "Dry mouth"],
        offers: [
          { pharmacyId: "careplus", price: 38, stock: "in-stock" },
          { pharmacyId: "wellpath", price: 40, stock: "in-stock" },
        ],
      },
      {
        id: "ibuprofen-400", name: "Ibuprofen 400mg", price: 32, mrp: 40, pack: "Strip of 10 tablets", form: "tablet", rule: "otc", concerns: ["pain", "fever"],
        manufacturer: "Medisun Labs", rating: 4.6, reviews: 980,
        description: "Ibuprofen is an anti-inflammatory pain reliever. Take it with food to protect your stomach.",
        uses: ["Muscle and joint pain", "Period pain", "Fever"],
        sideEffects: ["Stomach upset", "Heartburn"],
        offers: [
          { pharmacyId: "careplus", price: 34, stock: "in-stock" },
          { pharmacyId: "mediquick", price: 32, stock: "in-stock" },
        ],
      },
      {
        id: "azithromycin-500", name: "Azithromycin 500mg", price: 112, mrp: 140, pack: "Strip of 3 tablets", form: "tablet", rule: "prescription", concerns: ["fever", "infection"],
        manufacturer: "Cureline Pharma", rating: 4.5, reviews: 760,
        description: "Azithromycin is an antibiotic for certain bacterial infections, usually taken once a day for three days.",
        uses: ["Respiratory infections", "Skin infections"],
        sideEffects: ["Nausea", "Stomach pain", "Diarrhoea"],
        offers: [
          { pharmacyId: "careplus", price: 112, stock: "low-stock" },
          { pharmacyId: "mediquick", price: 118, stock: "in-stock" },
        ],
      },
      {
        id: "metformin-500", name: "Metformin 500mg", price: 28, mrp: 35, pack: "Strip of 20 tablets", form: "tablet", rule: "prescription", concerns: ["diabetes"],
        manufacturer: "Healix Life Sciences", rating: 4.6, reviews: 1900,
        description: "Metformin helps control blood sugar in type 2 diabetes alongside diet and exercise.",
        uses: ["Type 2 diabetes"],
        sideEffects: ["Nausea", "Loose stools when starting"],
        offers: [{ pharmacyId: "careplus", price: 28, stock: "in-stock" }],
      },
      {
        id: "ors-sachet", name: "ORS Electrolyte Powder", price: 21, mrp: 25, pack: "Pack of 4 sachets", form: "sachet", rule: "otc", concerns: ["fever"],
        manufacturer: "Novaris Generics", rating: 4.7, reviews: 640,
        description: "Oral rehydration salts replace fluids and electrolytes lost through fever, diarrhoea or heat.",
        uses: ["Dehydration", "Diarrhoea", "Heat exhaustion"],
        sideEffects: ["None expected when mixed as directed"],
        offers: [
          { pharmacyId: "careplus", price: 21, stock: "out-of-stock" },
          { pharmacyId: "mediquick", price: 22, stock: "out-of-stock" },
        ],
      },
      {
        id: "multivitamin", name: "Daily Multivitamin", price: 199, mrp: 249, pack: "Bottle of 30 tablets", form: "bottle", rule: "otc", concerns: ["vitamins"],
        manufacturer: "Healix Life Sciences", rating: 4.4, reviews: 520,
        description: "A once-daily multivitamin and mineral supplement to support everyday nutrition.",
        uses: ["Nutritional support"],
        sideEffects: ["Mild stomach upset"],
        offers: [
          { pharmacyId: "careplus", price: 199, stock: "in-stock" },
          { pharmacyId: "wellpath", price: 209, stock: "in-stock" },
        ],
      },
      {
        id: "alprazolam-05", name: "Alprazolam 0.5mg", price: 0, mrp: 0, pack: "Strip of 10 tablets", form: "tablet", rule: "restricted", concerns: [],
        manufacturer: "Cureline Pharma", rating: 0, reviews: 0,
        description: "A controlled medicine that is dispensed only through a special process under applicable law and pharmacy policy.",
        uses: [],
        sideEffects: [],
        offers: [],
      },
    ],
    labTests: [
      { id: "vitamin-d", name: "Vitamin D Test", price: 699, mrp: 999, mode: "Home collection", rating: 4.8, reviews: 4200, concerns: ["vitamins", "bone"] },
      { id: "cbc", name: "Complete Blood Count (CBC)", price: 499, mrp: 699, mode: "Home collection", rating: 4.7, reviews: 3100, concerns: ["fever"] },
      { id: "thyroid", name: "Thyroid Profile (T3, T4, TSH)", price: 699, mrp: 899, mode: "Home collection", rating: 4.6, reviews: 2200, concerns: ["thyroid"] },
      { id: "lipid", name: "Lipid Profile", price: 799, mrp: 999, mode: "Home collection", rating: 4.7, reviews: 1900, concerns: ["heart"] },
    ],
    labs: [
      { id: "healthplus", name: "HealthPlus Diagnostics", rating: 4.8, reviews: 7200, mode: "Home collection", turnaround: "Reports in 24 hrs", distance: "1.8 km", verified: true },
      { id: "citycare", name: "CityCare Labs", rating: 4.6, reviews: 3100, mode: "Home or centre", turnaround: "Reports in 36 hrs", distance: "3.4 km", verified: true },
      { id: "quicktest", name: "QuickTest Labs", rating: 4.2, reviews: 410, mode: "Centre visit", turnaround: "Reports in 48 hrs", distance: "2.2 km", verified: false },
    ],
    homeCare: [
      { id: "nurse-visit", name: "Nurse Visit", price: 499, unit: "visit", rating: 4.8, reviews: 1300, mode: "Same-day slots", concerns: ["fever"] },
      { id: "physiotherapy", name: "Physiotherapy", price: 699, unit: "session", rating: 4.7, reviews: 980, mode: "45-minute session", concerns: ["bone", "pain"] },
      { id: "injection-service", name: "Injection at Home", price: 299, unit: "visit", rating: 4.6, reviews: 720, mode: "Prescription needed", concerns: [] },
      { id: "elderly-care", name: "Elderly Care", price: 999, unit: "day", rating: 4.7, reviews: 540, mode: "Trained caregivers", concerns: ["heart"] },
    ],
    healthPackages: [
      { id: "full-body", name: "Full Body Checkup", tests: 72, price: 1499, mrp: 2999, rating: 4.7, reviews: 5200, mode: "Home collection", concerns: ["vitamins", "thyroid", "heart"] },
      { id: "womens-wellness", name: "Women's Wellness", tests: 58, price: 1999, mrp: 3499, rating: 4.6, reviews: 1800, mode: "Home collection", concerns: ["thyroid", "vitamins"] },
      { id: "heart-health", name: "Heart Health Package", tests: 34, price: 1299, mrp: 2199, rating: 4.7, reviews: 1100, mode: "Home collection", concerns: ["heart"] },
      { id: "senior-care", name: "Senior Citizen Checkup", tests: 64, price: 1799, mrp: 3199, rating: 4.5, reviews: 950, mode: "Home collection", concerns: ["bone", "heart"] },
    ],
    // Signed-in demo state: one prescription order waiting on the pharmacist.
    activeOrder: {
      id: "CN123456",
      // Medicine ids in this order. Home derives the summary line and flags these items as "in review".
      medicineIds: ["amoxicillin-500", "vitamin-d3-60k"],
      pharmacyId: "careplus",
      stage: 1,
    },
    lastOrder: { medicineId: "paracetamol-500" },
    // The prescription behind the active order above, as the journey store first sees it.
    seedPrescription: {
      id: "RX-48213",
      orderRef: "CN123456",
      fileName: "prescription_dr_sharma.jpg",
      fileSizeKb: 1240,
      uploadedMinutesAgo: 12,
    },
    // Past orders for the history screen. Lines reference medicines and pharmacies above.
    orderHistory: [
      {
        id: "CN123401", daysAgo: 3, status: "delivered", addressId: "home", slotId: "standard", paymentMethod: "upi",
        lines: [{ medicineId: "paracetamol-500", pharmacyId: "careplus", quantity: 2 }],
      },
      {
        id: "CN123389", daysAgo: 5, status: "payment-failed", addressId: "home", slotId: "express", paymentMethod: "card",
        lines: [{ medicineId: "cetirizine-10", pharmacyId: "careplus", quantity: 1 }],
      },
      {
        id: "CN123377", daysAgo: 9, status: "cancelled", addressId: "work", slotId: "standard", paymentMethod: "upi",
        lines: [
          { medicineId: "ibuprofen-400", pharmacyId: "mediquick", quantity: 1 },
          { medicineId: "multivitamin", pharmacyId: "careplus", quantity: 1 },
        ],
      },
    ],
    addresses: [
      { id: "home", label: "Home", line1: "12, Green Park, 3rd Street", line2: "Chennai 600028", phone: "+91 98765 43210" },
      { id: "work", label: "Work", line1: "4th Floor, Olympia Tech Park, Guindy", line2: "Chennai 600032", phone: "+91 98765 43210" },
    ],
    deliverySlots: [
      { id: "standard", label: "Today", detail: "6–8 PM", fee: 0 },
      { id: "express", label: "Within 1 hour", detail: "Express", fee: 30 },
      { id: "later", label: "Later", detail: "Choose a slot", fee: 0 },
    ],
    laterSlots: ["Tomorrow, 8–10 AM", "Tomorrow, 6–8 PM", "Day after, 8–10 AM"],
    paymentMethods: [
      { id: "upi", label: "UPI", detail: "PhonePe, Google Pay, Paytm", icon: "upi" },
      { id: "card", label: "Cards", detail: "Visa, Mastercard, RuPay", icon: "card" },
      { id: "wallet", label: "Wallets", detail: "Paytm, Amazon Pay", icon: "wallet" },
      { id: "cod", label: "Cash on delivery", detail: "Pay when it arrives", icon: "cash" },
    ],
    wallets: ["Paytm", "Amazon Pay"],
    savedCard: "Visa •••• 4242",
    delivery: { fee: 25, freeAbove: 199 },
    coupons: [{ code: "CARE10", percent: 10, maxDiscount: 50, description: "10% off items, up to ₹50" }],
    // Fictional courier shown once an order is out for delivery.
    deliveryPartner: { name: "Ravi Kumar", vehicle: "TN 09 AB 1234", phone: "+919876543210" },
    // Home "Popular services near you", in display order.
    popular: [
      { kind: "lab-test", id: "vitamin-d" },
      { kind: "medicine", id: "paracetamol-500" },
      { kind: "medicine", id: "amoxicillin-500" },
      { kind: "home-care", id: "nurse-visit" },
      { kind: "lab-test", id: "cbc" },
      { kind: "home-care", id: "physiotherapy" },
    ],
    // Home "Recommended providers", in display order.
    recommended: [
      { kind: "doctor", id: "priya-sharma" },
      { kind: "pharmacy", id: "careplus" },
      { kind: "lab", id: "healthplus" },
      { kind: "doctor", id: "sneha-kapoor" },
      { kind: "pharmacy", id: "mediquick" },
      { kind: "lab", id: "citycare" },
    ],
  },
} as const;

export type ProductConfig = typeof productConfig;
